### ISSUE TITLE
Map UI error when rotating and animation skipping / lagging

### ISSUE THREAD

**Issue by maeishoj** [ffwdme/ffwdme.js#28] opened 2016-10-10 10:16 UTC
Hi there, as promised here the issue i mentioned earlier...

I was with my iPad and as I drove and the cursor position updates, it is not a fluid movement like in your demo, but it jumps back and forth, like an elastic band :/

Also you can see that the map as it rotates, its edges become GRAY! and if I tap on them often it "refreshes" back the map.

Now, I am not sure why im getting this, do you have any idea?

If not, perhaps pointing me in the right direction ?

![img_0003](https://cloud.githubusercontent.com/assets/1631903/19255339/c719105e-8f11-11e6-89a5-2b95991fa71e.PNG)
![img_0005](https://cloud.githubusercontent.com/assets/1631903/19255340/c719ec2c-8f11-11e6-9b2f-c50711322343.PNG)

**Comment by maeishoj** [comment] 2016-10-12 09:55
The gray area started to be ok now. I had also some bad div creating unnecessary space. However the issue persists. As I drive, the map jerks back and forth. It seems that it either updates the position so often that it tries to redraw very often or that leaflet has some panning or fitbound().. Any ideas?

**Comment by fabrik42** [comment] 2016-10-12 09:56
So just to clarify: The map bounces, but the position updates themselves make sense? Or does the position keep jump around back and forth and the map just follows?

**Comment by maeishoj** [comment] 2016-10-12 10:04
So the cursor (representing the vehicle) follows the path correctly (although i am not sure what is the criteria to trigger the route recalculation because it seems as it may be quite slow to recognize it's off the route. Basically everyone works rather well, but as the cursor moves, the map or "map bounding box" (for lack of better words) kinda jerks back and forth. Could it be the autozoom? How do I use actually the various modules?

**Comment by fabrik42** [comment] 2016-10-12 10:12
Ok. To be honest, I never tried the map rotation on an iPad. So in your case, you should disable map rotation for now and check if it works without. If it works, you can be sure this bug is caused by the map rotation and you should have a look at this file: https://github.com/ffwdme/ffwdme.js/blob/master/src/components/map_rotator/index.js

The rerouting is determined by the auto reroute component here: https://github.com/ffwdme/ffwdme.js/blob/master/src/components/auto_reroute/index.js#L71

Another question that comes to my mind: Are you really sure that you are using the GPS sensor of the iPad? I had problems with this before. Please read this to make sure this does not happen to you: https://stackoverflow.com/questions/15234473/ios6-mobile-safari-accuracy-and-update-periods-of-geolocation-watchposition

**Comment by maeishoj** [comment] 2016-10-12 10:18
Hey! 

So in regards to the mapRotator, I believe it is turned off today and still doesn't help. 1 out.

I will try the last link.

**Comment by maeishoj** [comment] 2016-10-13 05:02
Hey @fabrik42  so the last link wasn't my issue at all. I am debugging the ipad via usb cable and via safari on my mac and the position get updated super fast. 

Regarding my issue, what I am doing is the moment i reach my desired location, and click next, I get re-routed to a new location and this is where I mostly notice this issue. I am going to upload a video about it so maybe it helps you understand what the problem is. I am really not sure how to tackle it yet so if you have any idea after you see the video, that would be great.

https://youtu.be/9HJNehnWzBQ

**Comment by maeishoj** [comment] 2016-10-13 21:23
Btw, why do you use that window.widget with all those components in the demo? is that required? Also why if I give the map a big size in order to have the rotator not ***** up when turning, it is centered in the center of the map as opposed on the cursors? any tips on how to fix this? 

I appreciate the help.

**Comment by maeishoj** [comment] 2016-10-14 01:53
So I actually found out how this happens. I have seberal waypoints i have to visit. When i initialize ffwdme, I immediately start navigation to the first waypoint, and all goes smooth. Once I reach that point and click to "go to next location", i re-route to a new destination with the following:

`var route = new ffwdme.routingService({
            dest: {
                lat: lat,
                lng: lng
            }
        }).fetch();`

It does re-route correctly but doesn't clear the previous flags and it starts "flickering" the screen back and forth and it also draw that narrow red line and keeps it anchored to some other (most previous) location. 

It's so close to work well..

**Comment by fabrik42** [comment] 2016-10-14 11:12
Do you use the new route at all?

I think the code example in the demo is misleading. The `fetch` method does not return a route, as it is an asychronous operation. You need to set up a listener beforehand.

You would need to do something like:

``` javascript
ffwdme.on('routecalculation:success', function(response) {
  ffwdme.navigation.setRoute(response.route).start();
});

new ffwdme.routingService({
  dest:  { lat: lat, lng: lng }
}).fetch();
```

**Comment by nunovelosa** [comment] 2016-10-14 13:21
@fabrik42 why don't you answer me ?

**Comment by maeishoj** [comment] 2016-10-14 17:26
@fabrik42 Yes I do that, just in different methods, I did not want to paste everything.. If you do it this way, where at each stop, you click a button and re-generate a new route, the map will start to do some weird things (that you can only see by actually driving, not from the computer screen, simulating or updating the position)... Right now I actually made it work by doing `ffwdme.navigation.reroute({}, newLocation.address.lat, newLocation.address.lon);` instead of making a new route. Its not optimal as it doesn't clear the flag on map (which i am now hiding) but at least it does the job. This removes any "flickering" or "jerking" of the map when going to next location or when re-routing. the map rotator also works (although when rotating it rotates the div it's in it, and thereby shows a few white corners while it rotates, but that's fine).

The next thing i have to look into is why the re-routing is rather slow to kick-in (takes a while before the helper line is gone and the re-route is rendered) and is often times not very accurate (i.e. if I am going straight and I surpass my endpoint and I keep driving straight past it, it will say just continue straight on the same road, although it means to say "behind you").

**Comment by fabrik42** [comment] 2016-10-24 16:17
I linked to the component that's responsible for the rerouting above. It should be simple to modify it for your needs.

**Comment by maeishoj** [comment] 2016-10-24 19:38
Thanks.

Btw I wanted to remove the polyline path drawn "behind me" as the cursor moves forward, so what I did is this:

var route = e.navInfo.route;
route.directions[0].path[0] = new L.LatLng(p.lat, p.lng);
this.drawPolylineOnMap(route);

in the navigationOnRoute on line 1193 or so

so everytime it's on route, it takes the starting position of the polyline path, the current GPS location. And works well.

Unfortunately, when it goes off route, and redirects, it then maintains another path line to where it was now drawing two paths. 

Any chance you have an idea why that is and how do i tackle this? 

Appreciate your help!

**Comment by maeishoj** [comment] 2016-10-24 21:11
I actually solved it by only rendering the polyline in the "onroute" method from the current cursor location to the destination and without the polyline being created in the drawroute.

**Comment by fabrik42** [comment] 2016-10-25 13:21
Yes, this is a good approach! You could also use the mapped position from the object passed to the event: https://github.com/ffwdme/ffwdme.js/blob/master/src/core/navigation_info.js#L21

**Comment by maeishoj** [comment] 2016-10-25 23:40
Hey there. my approach seemed that it was working but it doesn't... :/ it only does that for the first segment but the moment it moves to the next one :/ I have to see what's up with that. 

Also do you happen to know why is it that if I go in a straight line (road) opposite to what my destination is, and the re-routing kicks in, it thinks im still on the same path and wants me to turn around as opposed to re-route on a different street... Is there a way to factor in the heading of the geoposition in the recalculation?

**Comment by fabrik42** [comment] 2016-11-01 15:00
Yes, this is the anchor point that is used in the auto reroute component I linked above: https://github.com/ffwdme/ffwdme.js/blob/master/src/components/auto_reroute/index.js#L75

**Comment by fabrik42** [comment] 2017-01-30 13:14
Closing this for now. Please reopen, if there is new information on the topic. :)

Cheers,
Christian

**Closed as completed by fabrik42** 2017-01-30 13:14 UTC
